import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ejercicio justR-pokemon - Sergio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1>Ejercicio justR-pokemon - Sergio</h1>
        <h2>Bienvenidos a Todos!</h2>
        <img
          src="https://phantom-marca.unidadeditorial.es/9265f61b4b94fe9d71cff8ad932d3a7d/resize/660/f/webp/assets/multimedia/imagenes/2021/02/28/16145196328904.jpg"
          alt="imagen-pokemons"
        />
      </main>
    </div>
  );
}
